In [ ]:
#creating a numpy array
import numpy as np
print(np.__version__)
a = np.array([1,2,3,4], dtype=np.int32)
print(a.shape)
print(a.ndim)
print(a)

2.4.6


NameError: name 'int32' is not defined

In [18]:
#creating different type of arrays using numpy

zeros = np.zeros((3,4))
print("zero matrix :\n",zeros)

ones = np.ones((2,3))
print("ones matrix :\n",ones)

a = np.full((5,5),15)
print("matrix containing 15 :\n",a)

random = np.random.random((2,2))
print(random)

zero matrix :
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones matrix :
 [[1. 1. 1.]
 [1. 1. 1.]]
matrix containing 15 :
 [[15 15 15 15 15]
 [15 15 15 15 15]
 [15 15 15 15 15]
 [15 15 15 15 15]
 [15 15 15 15 15]]
[[0.50514665 0.71545406]
 [0.08344128 0.86472669]]
